name: basecleanflutter

packages:
  - ./**

ignore:
  - .fvm/**

command:
  bootstrap:
    runPubGetInParallel: false

scripts:
  # build runner build (updated for newer Flutter/Melos)
  build_all:
    run: melos exec --depends-on="build_runner" -- dart run build_runner build
    description: build_runner build all modules.

  build_data:
    run: melos exec --fail-fast --scope="*data*" --depends-on="build_runner" -- dart run build_runner build
    description: build_runner build data module.

  build_domain:
    run: melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" -- dart run build_runner build
    description: build_runner build domain module.

  build_app:
    run: melos exec --fail-fast --scope="*app*" --depends-on="build_runner" -- dart run build_runner build
    description: build_runner build app module.

  build_shared:
    run: melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" -- dart run build_runner build
    description: build_runner build shared module.

  # build runner watch (updated syntax)
  watch_all:
    run: melos exec --depends-on="build_runner" -- dart run build_runner watch
    description: build_runner watch all modules.

  watch_data:
    run: melos exec --fail-fast --scope="*data*" --depends-on="build_runner" -- dart run build_runner watch
    description: build_runner watch data module.

  watch_domain:
    run: melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" -- dart run build_runner watch
    description: build_runner watch domain module.

  watch_app:
    run: melos exec --fail-fast --scope="*app*" --depends-on="build_runner" -- dart run build_runner watch
    description: build_runner watch app module.

  watch_shared:
    run: melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" -- dart run build_runner watch
    description: build_runner watch shared module.

  # build runner build --delete-conflicting-outputs
  force_build_all:
    run: |
      echo "🔧 Building all modules with build_runner 2.7.1..."
      echo "📦 Building data module..."
      melos run force_build_data
      echo "📦 Building domain module..."
      melos run force_build_domain
      echo "📦 Building shared module..."
      melos run force_build_shared
      echo "📦 Building app module..."
      melos run force_build_app
      echo "✅ All modules built successfully with build_runner 2.7.1 + auto_route_generator 10.2.4!"
    description: build_runner build all modules with updated compatible versions.

  force_build_data:
    run: melos exec --fail-fast --scope="*data*" --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
    description: build_runner build data module.

  force_build_domain:
    run: melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
    description: build_runner build domain module.

  force_build_app:
    run: melos exec --fail-fast --scope="*app*" --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
    description: build_runner build app module.

  force_build_shared:
    run: melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
    description: build_runner build shared module.

  # build runner watch --delete-conflicting-outputs (updated syntax)
  force_watch_all:
    run: melos exec --depends-on="build_runner" -- dart run build_runner watch --delete-conflicting-outputs
    description: build_runner watch all modules.

  force_watch_data:
    run: melos exec --fail-fast --scope="*data*" --depends-on="build_runner" -- dart run build_runner watch --delete-conflicting-outputs
    description: build_runner watch data module.

  force_watch_domain:
    run: melos exec --fail-fast --scope="*domain*" --depends-on="build_runner" -- dart run build_runner watch --delete-conflicting-outputs
    description: build_runner watch domain module.

  force_watch_app:
    run: melos exec --fail-fast --scope="*app*" --depends-on="build_runner" -- dart run build_runner watch --delete-conflicting-outputs
    description: build_runner watch app module.

  force_watch_shared:
    run: melos exec --fail-fast --scope="*shared*" --depends-on="build_runner" -- dart run build_runner watch --delete-conflicting-outputs
    description: build_runner watch shared module.

  l10n:
    run: melos exec --fail-fast --scope="*resources*" --flutter -- flutter pub run intl_utils:generate
    description: Generates l10n for all app packages.

  test:
    run: melos exec --fail-fast --dir-exists="test" -- flutter test
    description: Run all tests.

  pub_upgrade:
    run: melos exec --fail-fast -- flutter pub upgrade
    description: Run pub upgrade on all module.

  test_app:
    run: melos exec --fail-fast --scope="*app*" -- flutter test
    description: Run test app module.
  
  test_domain:
    run: melos exec --fail-fast --scope="*domain*" -- flutter test
    description: Run test domain module.
  
  test_data:
    run: melos exec --fail-fast --scope="*data*" -- flutter test
    description: Run test data module.
  
  test_shared:
    run: melos exec --fail-fast --scope="*shared*" -- flutter test
    description: Run test shared module.



  test_coverage:
    run: melos exec --fail-fast --dir-exists="test" -- flutter test --coverage && lcov --remove coverage/lcov.info '**/*.freezed.dart' '**/*.g.dart' '**/*.graphql.dart' '**/*.part.dart' '**/*.config.dart' '**/*_event.dart' '**/*_state.dart' '**/generated/*' '**/routes/*' '**/l10n/*' '**/config/*' '**/di/*' -o coverage/lcov.info && genhtml coverage/lcov.info --output=coverage && open coverage/index.html
    description: Run test coverage.



  pub_get_data:
    run: melos exec --fail-fast --scope="*data*" -- flutter pub get
    description: pub get data module.
    
  pub_get_domain:
    run: melos exec --fail-fast --scope="*domain*" -- flutter pub get
    description: pub get domain module.

  pub_get_app:
    run: melos exec --fail-fast --scope="*app*" -- flutter pub get
    description: pub get app module.

  pub_get_shared:
    run: melos exec --fail-fast --scope="*shared*" -- flutter pub get
    description: pub get shared module.

  # Code formatting
  format:
    run: melos exec --fail-fast -- dart format .
    description: Format code across all packages.

  format_check:
    run: melos exec --fail-fast -- dart format --set-exit-if-changed .
    description: Check if code is properly formatted.

  # Static analysis
  analyze_app:
    run: melos exec --fail-fast --scope="*app*" -- flutter analyze --fatal-infos
    description: Analyze app module.

  analyze_data:
    run: melos exec --fail-fast --scope="*data*" -- flutter analyze --fatal-infos
    description: Analyze data module.

  analyze_domain:
    run: melos exec --fail-fast --scope="*domain*" -- flutter analyze --fatal-infos
    description: Analyze domain module.

  analyze_shared:
    run: melos exec --fail-fast --scope="*shared*" -- flutter analyze --fatal-infos
    description: Analyze shared module.

  analyze:
    run: melos exec --fail-fast -- flutter analyze --fatal-infos
    description: Analyze all packages.


