name: resources
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 6.2.0
  dart_style: 2.3.6

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  intl: 0.19.0
  intl_utils: 2.8.7

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n
