name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 8.2.0
  injectable: ^2.4.0
  meta: ^1.9.1
  resources:
    path: ../resources
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.6.0
  mocktail: 1.0.4
