name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  async: 2.13.0

dependencies:
  async: 2.13.0
  dartx: 1.2.0
  flutter:
    sdk: flutter
  get_it: 8.2.0
  injectable: ^2.4.0
  meta: ^1.9.1
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
  tuple: 2.0.2

dev_dependencies:
  build_runner: ^2.9.0
  # custom_lint: 0.6.0  # Tạm comment để upgrade build_runner
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.6.0
  mocktail: 1.0.4
  # nals_lints:  # Tạm comment để fix analyzer conflict
  #   path: ../nals_lints
