name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependency_overrides:
  device_info_plus: ^10.1.0
  js: ^0.7.0
  win32: ^5.8.0
dependencies:
  auto_route: ^10.1.2
  cached_network_image: 3.4.1
  cupertino_icons: 1.0.8
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_local_notifications: 19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.9.3
  flutter_svg: 2.2.1
  get_it: 8.2.0
  infinite_scroll_pagination: 4.0.0  # Rollback to stable API
  initializer:
    path: ../initializer
  injectable: ^2.4.0
  resources:
    path: ../resources
  rxdart: 0.28.0
  shared:
    path: ../shared
dev_dependencies:
  auto_route_generator: ^10.2.4
  bloc_test: 10.0.0
  build_runner: ^2.7.1
  flutter_gen_runner: ^5.4.0 
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_native_splash: 2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.6.0
  mocktail: 1.0.4

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_length: 160

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
#  fonts:
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400
