default_platform(:ios)

platform :android do
  desc "Build Android APK for any flavor"
  lane :build_android_apk do |options|
    flavor = options[:flavor] || "production"
    gradle_task = "assemble#{flavor.capitalize}Release"
    sh("cd ../app/android && ./gradlew #{gradle_task}")
  end

  desc "Build Android AAB for any flavor"
  lane :build_android_aab do |options|
    flavor = options[:flavor] || "production"
    gradle_task = "bundle#{flavor.capitalize}Release"
    sh("cd ../app/android && ./gradlew #{gradle_task}")
  end

  desc "Build both APK and AAB for any flavor"
  lane :build_android_all do |options|
    build_android_apk(options)
    build_android_aab(options)
  end
end

platform :ios do
  desc "Build iOS Development build for any flavor"
  lane :build_flavor do |options|
    flavor = options[:flavor] || "Production"
    scheme = flavor # Schema của bạn: Production, Qa, Staging, Develop
    output_name = "BaseFlutter_#{flavor}.ipa"
    import_certificate(
  certificate_path: "fastlane/certs/cert.p12",
      certificate_password: ENV["IOS_CERTIFICATE_PASSWORD"],
      keychain_name: "login.keychain-db",
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    build_app(
      workspace: "app/ios/Runner.xcworkspace",
      scheme: scheme,
      export_method: "development",
      output_directory: "./build/ios",
      output_name: output_name
    )
  end
end

# Sử dụng: fastlane build_flavor flavor:Production hoặc flavor:Qa, flavor:Staging, flavor:Develop
# Sử dụng: fastlane build_android flavor:production hoặc flavor:qa, flavor:staging, flavor:develop
