default_platform(:ios)

platform :ios do
  desc "Build and release iOS app"
  lane :release do
    build_app(
      scheme: "BaseFlutter"
      # Thêm các option khác nếu cần
    )
    # Thêm các bước upload, sign, testflight nếu cần
  end
end
