default_platform(:ios)

platform :ios do
  desc "Build iOS Development build for any flavor"
  lane :build_flavor do |options|
    flavor = options[:flavor] || "Production"
    scheme = flavor # Schema của bạn: Production, Qa, Staging, Develop
    output_name = "BaseFlutter_#{flavor}.ipa"
    import_certificate(
      certificate_path: "./certs/cert.p12",
      certificate_password: ENV["IOS_CERTIFICATE_PASSWORD"],
      keychain_name: "login.keychain-db"
    )
    build_app(
      scheme: scheme,
      export_method: "development",
      output_directory: "./build/ios",
      output_name: output_name
    )
  end
end

# Sử dụng: fastlane build_flavor flavor:Production hoặc flavor:Qa, flavor:Staging, flavor:Develop