default_platform(:ios)

platform :ios do
  desc "Build and release iOS app"
  lane :release do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_team_id: ENV["DEVELOPMENT_TEAM"]
      # Thêm các option khác nếu cần
    )

    # Thêm các bước upload, sign, testflight nếu cần
  end
end
