default_platform(:ios)

platform :ios do
  desc "Build iOS Development build"
  lane :dev_build do
    build_app(
      scheme: "Runner",
      export_method: "development",
      output_directory: "./build/ios",
      output_name: "BaseFlutter.ipa",
      certificate_password: ENV["IOS_CERTIFICATE_PASSWORD"]
    )
  end
end