name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  android_id: 0.4.0
  async: 2.13.0
  dartx: 1.2.0
  decimal: 3.2.4
  device_info_plus: 12.1.0
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.4.1
  flutter_udid: 4.0.0
  injectable: ^2.4.0
  intl: 0.20.2
  mime: 2.0.0
  package_info_plus: 9.0.0
  path_provider: 2.1.5
  rxdart: 0.28.0
  timezone: 0.10.1
  url_launcher: 6.3.2

dev_dependencies:
  build_runner: ^2.5.4
  # custom_lint: 0.6.0  # Tạm comment để upgrade build_runner
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.6.0
  mocktail: 1.0.4
